### ISSUE TITLE
UnboundLocalError: local variable 'event' referenced before assignment

### ISSUE THREAD

**Issue by lynchdean** [lynchdean/pizzapool#11]
500 server error when form is submitted but form.is_valid() returns false

Trace:
2024-05-15 10:05:33,315: Internal Server Error: /events/200c2b61-2c52-4034-a998-3f73aa252b77/create-pizza-order/
Traceback (most recent call last):
  File "/home/pizzapool/pizzapool/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/pizzapool/pizzapool/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pizzapool/pizzapool/events/views.py", line 49, in create_pizza_order
    return render(request, 'events/create_pizza_order.html', {'form': form, 'event': event})
UnboundLocalError: local variable 'event' referenced before assignment

**Comment by lynchdean** [comment]
Followed the template linked below - so will move the assignment to event to the top of the method to avoid the error but keep the flow of the template. Will also do the same for the claim slices method, even though it is yet to show any errors in the logs. 
https://docs.djangoproject.com/en/5.0/topics/forms/#the-view
